# Практическая работа 7 (Тест)
## Тема: Описательные статистики

### Настройка окружения

In [309]:
import pandas as pd

## Часть 1

Набор данных [BikesData.csv](./BikesData.csv) содержит сведения о работе велопроката.

Описание переменных:

- **Data** - день/месяц/год (с 1 декабря 2017 года по 30 ноября 2018 года)
- **Hour** - час (от 0 до 24)
- **Temperature** - температура в градусах Цельсия
- **Humidity** - процент влажности
- **Wind speed** - скорость ветра м/сек
- **Rainfall** - осадки в виде дождя, мм
- **Snowfall** - осадки в виде снега, мм
- **Seasons** - сезон (Winter, Spring, Summer, Autumn)
- **Holiday** - рабочий или праздничный день (Holiday/No holiday)
- **Function Day** - рабочий или нерабочий день велопроката (Yes/No)
- **Rental Count** - количество велосипедов, взятых в аренду в этот час
- **Normal Humidity** - была ли влажность нормальной
- **Temperature Category** - категория температуры (Freezing (заморозки), Chilly (прохладно), Nice (идеальная), Hot (жарко))
- **Good Weather** - была ли погода хорошей.

In [310]:
bikes = pd.read_csv("BikesData.csv", parse_dates=["Date"])
bikes.head(1)

,Date,Hour,Temperature,Humidity,Wind speed,Rainfall,Snowfall,Seasons,Holiday,Functioning Day,Rental Count,Normal Humidity,Temperature Category,Good Weather
0,2017-12-01,0,-5.2,37,2.2,0.0,0.0,Winter,0,True,257,0,Freezing,0

### Вопрос 1
Для столбца **Rainfall** вычислите меры центральной тенденции. Дробные числа округлите до 2 знаков после запятой.

In [311]:
mean = round(bikes.Rainfall.mean(), 2)
median = round(bikes.Rainfall.median(), 2)
mode = bikes.Rainfall.mode().round(2)

print(f"Среднее арифметическое: {mean}")
print(f"Медиана: {median}")
print(f"Моды: {", ".join(map(str, mode))}")

Среднее арифметическое: 0.15
Медиана: 0.0
Моды: 0.0

### Вопрос 2
Укажите среднее число аренд велосипедов в 01:00 с хорошей погодой. В ответе укажите округленное целое число.

In [312]:
bikes_with_night_good_weather = bikes[(bikes.Hour == 1) & (bikes["Good Weather"] == 1)]

bikes_with_night_good_weather

round(bikes_with_night_good_weather["Rental Count"].mean())

631

### Вопрос 3
Укажите, какая погода (**Temperature Category**) преобладала весной.

In [313]:
bikes_spring = bikes[bikes.Date.dt.month.isin([3, 4, 5])]

bikes_spring["Temperature Category"].mode().to_list()

['Chilly']

### Вопрос 4
Определите суммарное число аренд велосипедов для каждого часа. Для получившихся значений вычислите меры вариативности. Дробные числа округлите до 2 знаков после запятой.

In [314]:
grouped_bikes_by_hour = bikes.groupby("Hour")["Rental Count"].sum()

range = grouped_bikes_by_hour.max() - grouped_bikes_by_hour.min()
quantiles = grouped_bikes_by_hour.quantile([0.25, 0.75])
iqr = round(quantiles[0.75] - quantiles[0.25], 2)
var = round(grouped_bikes_by_hour.var(ddof=0), 2)
std = round(grouped_bikes_by_hour.std(ddof=0), 2)

print(f"Размах: {range}")
print(f"Интерквартильный размах: {iqr}")
print(f"Дисперсия для генеральной совокупности: {var}")
print(f"Среднеквадратичное отклонение для генеральной совокупности: {std}")

Размах: 509593
Интерквартильный размах: 166152.25
Дисперсия для генеральной совокупности: 15876133226.41
Среднеквадратичное отклонение для генеральной совокупности: 126000.53

## Часть 2

Для успешного прохождения теста вам потребуется воспользоваться [данными](./MarvelComicCharacters.csv) персонажей вселенной Marvel, самостоятельно загрузив их в Python.

*Описание данных:*

- **name** — оригинальное имя персонажа вселенной Marvel
- **align** — принадлежность персонажа к доброй/злой/нейтральной стороне
- **eye** — описание глаз персонажа
- **hair** — описание волос персонажа
- **sex** — пол персонажа
- **appearances** — количество появлений персонажа
- **first_appearance** — год первого появления персонажа

In [315]:
characters = pd.read_csv("MarvelComicCharacters.csv", sep=";")
characters.head(1)

,name,align,eye,hair,sex,appearances,first_appearance
0,Spider-Man (Peter Parker),Добрый персонаж,Карие глаза,Каштановые волосы,Мужской персонаж,4043.0,1962.0

### Вопрос 1
Какова мода по переменной **align**?

In [316]:
characters["align"].mode().to_list()

['Злой персонаж']

### Вопрос 2
Укажите, верно ли следующее утверждение: для переменной **sex** можно определить медиану.

*Ответ*: Неверно

### Вопрос 3
Вам представлены утверждения о мерах центральной тенденции (среднее арифметическое, мода, медиана) для переменной **appearances**. Какое из них верно? Выберите один верный ответ.

*Варианты ответа*:

1. Для переменной **appearances** можно определить моду, но нельзя посчитать медиану.

2. Для переменной **appearances** можно рассчитать медиану, моду и среднее арифметическое.

3. Для переменной **appearances** можно посчитать только медиану.

4. Для переменной **appearances** нельзя рассчитать меры центральной тенденции.

5. Для переменной **appearances** можно определить моду, но нельзя посчитать среднее значение.

*Ответ*: 2

### Вопрос 4
Вам представлены утверждения о мерах разброса (размах и межквартильных размах) для переменной **hair**. Какое из них верно? Выберите один верный ответ.

*Варианты ответа*:

1. Для переменной **hair** невозможно посчитать обе меры разброса.

2. Для переменной **hair** можно определить размах, но нельзя посчитать межквартильный размах.

3. Для переменной **hair** невозможно определить размах, но можно посчитать межквартильный размах.

4. Для переменной **hair** можно посчитать обе меры разброса.

*Ответ*: 1

### Вопрос 5
Выберите только добрых персонажей и определите медиану по переменной **appearances**. Введите ответ в виде целого числа.

In [317]:
characters_kind = characters[characters["align"] == "Добрый персонаж"]

round(characters_kind.appearances.median())

5

### Вопрос 6
Найдите дисперсию по переменной **appearances**. Помните, что мы работаем с генеральной совокупностью. В ответ запишите число, округлите до целого.

In [318]:
round(characters.appearances.var(ddof=0))

9287

### Вопрос 7
Укажите, верно ли следующее утверждение: если убрать первые сто наблюдений в наших данных, то мода по переменной **eye** не изменится.

In [319]:
prev_mode = characters.eye.mode()
new_mode = characters.iloc[100:].eye.mode()

(prev_mode == new_mode).all()

np.True_

### Вопрос 8
Определите моду по переменной **hair**, затем выберите только тех персонажей, цвет волос которых соответствует найденной моде. По имеющемуся подмассиву данных по переменной **appearances** рассчитайте стандартное отклонение. Помните, что мы работаем с генеральной совокупностью. В ответ запишите число, округлите до целого.

In [320]:
hair_mode = characters.hair.mode()
characters_hair_mode = characters[characters.hair.isin(hair_mode)]

round(characters_hair_mode.appearances.std(ddof=0))

94

### Вопрос 9
Удaлитe прoпущeнныe знaчeния пo стoлбцу **appearances**. Рассчитайте мeжквaртильный рaзмaх пo пeрeмeннoй **appearances** для нейтральных пeрсoнaжeй (**align**).

In [321]:
cleaned_characters = characters.dropna(subset=["appearances"])
characters_neutral = cleaned_characters[
    cleaned_characters["align"] == "Нейтральный персонаж"
]

quantiles = characters_neutral.appearances.quantile([0.25, 0.75])

round(quantiles[0.75] - quantiles[0.25])

8

### Вопрос 10
Скoлькo выбрoсoв встрeчaeтся пo пeрeмeннoй **appearances**? Прeдвaритeльнo удaлитe прoпущeнныe знaчeния пo стoлбцу **appearances**, испoльзуйтe для нaхoждeния выбрoсoв мeжквaртильный рaзмaх.

In [322]:
quantiles = cleaned_characters.appearances.quantile([0.25, 0.75])
iqr = quantiles[0.75] - quantiles[0.25]

lower_iqr, upper_iqr = quantiles[0.25] - 1.5 * iqr, quantiles[0.75] + 1.5 * iqr

outliers_iqr = cleaned_characters[
    ~cleaned_characters.appearances.between(lower_iqr, upper_iqr)
]

len(outliers_iqr)

1938

### Вопрос 11
Нa oснoвe дaнных, пoлучeнных в предыдущем задании, укaжитe кoличeствo выбрoсoв пo пeрeмeннoй appearances для дoбрых пeрсoнaжeй.

In [323]:
len(outliers_iqr[outliers_iqr["align"] == "Добрый персонаж"])

944

### Вопрос 12
Скoлькo выбрoсoв пoлучится пo пeрeмeннoй **appearances**, если для нaхoждeния использовать четыре срeднeквaдрaтичных oтклoнeния oт срeднeгo? Прeдвaритeльнo удaлитe прoпущeнныe знaчeния пo стoлбцу **appearances**. Ввeдитe oтвeт в видe цeлoгo числa.

In [324]:
mean = cleaned_characters.appearances.mean()
std = cleaned_characters.appearances.std(ddof=0)

lower_4std, upper_4std = mean - std * 4, mean + std * 4

outliers_4std = cleaned_characters[
    ~cleaned_characters.appearances.between(lower_4std, upper_4std)
]

len(outliers_4std)

87

### Вопрос 13
Срaвнитe медиану пo пeрeмeннoй **appearances** в двух дaтaфрeймaх — бeз выбрoсoв, oпрeдeлeнных пo мeжквaртильнoму рaзмaху, и бeз выбрoсoв, oпрeдeлeнных пo трeм срeднeквaдрaтичным oтклoнeниям oт срeднeгo. Будeм считaть, чтo грaницы дaтaфрeймoв бeз выбрoсoв сoдeржaт знaчeния вeрхних и нижних грaниц, oпрeдeлeнных пo мeжквaртильнoму рaзмaху или срeднeквaдрaтичнoму oтклoнeнию oт срeднeгo. В oтвeт зaпишитe числo (нaибoльшую медиану из двух), oкруглитe дo цeлoгo.

In [327]:
no_outliers_iqr = cleaned_characters[
    cleaned_characters.appearances.between(lower_iqr, upper_iqr)
]

mean = cleaned_characters.appearances.mean()
std = cleaned_characters.appearances.std(ddof=0)

lower_3std, upper_3std = mean - std * 3, mean + std * 3

no_outliers_3std = cleaned_characters[
    cleaned_characters.appearances.between(lower_3std, upper_3std)
]

round(max(no_outliers_iqr.appearances.mean(), no_outliers_3std.appearances.mean()))

11

### Вопрос 14
Укажите кол-во дoбрых мужских пeрсoнaжeй с белым цветом волос после удaления выбрoсов пo пeрeмeннoй **appearances**. Прeдвaритeльнo удaлитe прoпущeнныe знaчeния пo стoлбцу **appearances**, испoльзуйтe для нaхoждeния выбрoсoв мeжквaртильный рaзмaх.

In [ ]:
characters_kind_white_hair = no_outliers_iqr[
    (no_outliers_iqr["align"] == "Добрый персонаж")
    & (no_outliers_iqr.hair == "Белые волосы")
]

len(characters_kind_white_hair)

200

## Часть 3

### Вопрос 1
Предположим, среднеквадратичное отклонение равно 2.5, а среднее — 30. Рассчитайте Z-оценку для значения 35.

*Решение*:

$
z = \frac{x - \mu}{\sigma} = \frac{35 - 30}{2.5} = \frac{5}{2.5} = 2
$

*Ответ*: 2

### Вопрос 2
Предположим, что z-оценка равна 7.8, среднее равно 12, а среднеквадратичное отклонение равно 3. Чему будет равно значение наблюдения?

*Решение*:

$
x = z \cdot \sigma + \mu = 7.8 \cdot 3 + 12 = 23.4 + 12 = 35.4
$

*Ответ*: 35.4